Sources/HTTPRoute.swift, Sources/HTTPServer.swift
Add a little trick by using `ExpressibleByStringLiteral`.
This still allows the usage:
```
await server.appendHandler(for: "GET /mock", handler: .file(named: "mock.json"))
```
and also enable:
```
await server.appendHandler(for: Router(method: .GET, path: "/mock"), handler: .file(named: "mock.json"))
```
=> Supporting creating router by http method and path

Sources/HTTPHandler.swift, Sources/URLSession+Async.swift
This PR creates a backward compatible async func in `URLSession` extension with the same signature to the function in iOS 15. So that making it simpler to clean up code in future.
The code is inspired and borrowed from here: https://www.swiftbysundell.com/articles/making-async-system-apis-backward-compatible/
=> Simplify code to make URLSession api backward compatible

README.md, Sources/HTTPRoute.swift, Tests/HTTPRouteTests.swift
Adds the ability for routes to pattern match against the query items of `HTTPRequest`.
This allows for handlers to be added for more specific routes;
```swift
await server.appendRoute("GET /meal?side=fish", to: .file(named: "meal-fish.json"))
await server.appendRoute("GET /meal?side=chips", to: .file(named: "meal-chips.json"))
```
`HTTPRoute.QueryItem` is similar to `HTTPRequest.QueryItem` except that the routes value can be a wildcard component with the same matching semantics as the path components.
Because HTTP query parameters can be repeated, the route matches if the specific query item exists at least once.
`GET /meal?side=chips&side=peas&side=chips`
=> Including QueryItems within Routes

README.md, Sources/HTTPHeader.swift, Sources/HTTPRoute.swift, Tests/HTTPRouteTests.swift
Adds the ability for routes to pattern match against the headers of `HTTPRequest`.
This allows for handlers to be added for more specific routes;
```swift
let json = HTTPRoute("*", headers: [.contentType: "application/json"])
let xml  = HTTPRoute("*", headers: [.contentType: "application/xml"])
await server.appendRoute(json, to: .file(named: "sample.json"))
await server.appendRoute(xml, to: .file(named: "sample.xml"))
```
Header values can be wildcards routing requests when the header exists;
```swift
let auth = HTTPRoute("*", headers: [.authorization: "*"])
await server.appendRoute(auth, to: .file(named: "authenticated.html"))
await server.appendRoute("*", to: .file(named: "guest.html"))
```
=> HTTPHeaders within Routes

Sources/HTTPBodyPattern.swift, Sources/HTTPRoute.swift, Tests/HTTPBodyPatternTests.swift, Tests/HTTPRouteTests.swift
Adds the ability for routes to pattern match against the body of `HTTPRequest`.
On Darwin platforms `JSONPredicatePattern` can be used to create routes;
```swift
let route = HTTPRoute("GET /mock", body: .json(where: "food == 'fish'"))
```
to accept a JSON body like so;
```json
{"age": 45, "food": "fish"}
```
The pattern decodes the body use `JSONSerialization` and then uses `NSPredicate` for evaluation
`NSPredicate` does not have feature parity on Linux platforms, but it is possible to write a custom body pattern:
```swift
public protocol HTTPBodyPattern: Sendable {
func evaluate(_ body: Data) -> Bool
}
```
=> JSON predicate within Routes

Sources/HTTPLogging+OSLog.swift, Sources/HTTPLogging.swift, Sources/HTTPServer.swift, Tests/HTTPLogging+OSLogTests.swift
I thought it would be useful to add extra levels of logging.
Modified the server.start's logError to be a Critical level since the server will be stopped.
Below is a screenshot showing the output from the unit-test that uses oslog and being captured using the `log` tool.
=> Added extra levels of log messages: debug, warning and critical.

.swiftpm/xcode/xcshareddata/xcschemes/FlyingFox.xcscheme, Sources/HTTPConnection.swift, Sources/HTTPServer.swift, Sources/Socket/Socket+Darwin.swift, Sources/Socket/Socket+Glibc.swift, Sources/Socket/Socket.swift, Sources/Socket/SocketAddress.swift, Sources/Socket/SocketError.swift, Tests/HTTPConnectionTests.swift, Tests/HTTPServerTests.swift, Tests/Socket+Pair.swift, Tests/SocketAddress+Glibc.swift, Tests/SocketAddressTests.swift, Tests/SocketErrorTests.swift, Tests/SocketTests.swift
Adds support for starting the HTTP server using a supported `sockaddr` type
- `sockaddr_in`
- `sockaddr_in6`
- `sockaddr_un`
Adds `protocol SocketAddress` to formalise the the relationship of these types.
=> Adds Support for AF_UNIX sockets

.github/workflows/build.yml
Swift 5.6 docker containers are now available
=> Swift 5.6 on linux

Sources/HTTPServer.swift, Sources/Socket/PollingSocketPool.swift, Sources/Socket/Socket+WinSock2.swift, Sources/Socket/SocketAddress.swift
Adds experimental support for Sockets on Windows using WinSock2.
Known Issues: WebSockets do not work but it is a start 🤠.
=> Experimental Windows Support (WinSock2)

FlyingFox/Sources/HTTPDecoder.swift, FlyingFox/Tests/HTTPDecoderTests.swift
As per RFC-3986 5.2.4 (Remove Dot Segments), we want to remove `..`s. We can use Foundation's `URL.standardized` features for that.
However, I am sleepy, so this may have missed something obvious.
Fixes swhitty/FlyingFox/issues/24
=> Standardize paths, fix path traversal

FlyingSocks/Sources/Socket.swift
The issue was caused by incorrect handling of data slices with non-zero start indices and could lead to arbitrary memory being leaked to the socket. See #26 for details.
=> Fix security vulnerability in Socket.write (#26)

FlyingFox/Sources/WebSocket/SHA1.swift
The custom SHA1 hashing algorithm that FlyingFox uses when CryptoKit isn't available crashes when passed a data slice over 64 bytes in length. This is because [the first for loop in `SHA1.hash`](https://github.com/stackotter/FlyingFox/blob/aea293620ab5393c967f195d3e6d17e86796d216/FlyingFox/Sources/WebSocket/SHA1.swift#L106) assumes that the data's first index is 0.
To fix this I have added two lines to the start of the method which make a copy of the data to ensure that the algorithm is operating on regular data and not a slice.
The code below demonstrates the issue. The expected behaviour is that `slice` and `sliceEquivalent` have the same SHA1 hash. But what actually happens is that `SHA1.hash(data: slice)` crashes.
```swift
extension Data {
func hexEncodedString() -> String {
return …
```
=> Fix `SHA1.hash` for data slices on non-CryptoKit platforms

FlyingFox/Sources/Handlers/WebSocketHTTPHander.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingFox/Tests/Handlers/WebSocketHandlerTests.swift
[RFC 6455 section 4.2.1](https://datatracker.ietf.org/doc/html/rfc6455#section-4.2.1) prescribes which headers are mandatory for a WebSocket handshake request to be correct. It also details what each of these headers should contain. This PR brings `WebSocketHTTPHander` up to spec (which has a typo by the way, but I didn't change that to keep this PR focussed).
I have documented the new code in a way that makes it easy to match up each check with its corresponding RFC rule (see `WebSocketHTTPHander.verifyHandshakeRequestHeaders`).
There is one conundrum that I ran into while implementing the checks, which is that rule 1 mandates that websocket connections must begin as `GET` requests, however in FlyingFox the method for websocket endpoints is up to users of the framework. We could add some …
=> Conform WebSocketHTTPHandler to RFC 6455 section 4.2.1

FlyingFox/Sources/HTTPHandler.swift, FlyingFox/Sources/Handlers/WebSocketHTTPHandler.swift, FlyingFox/Tests/Handlers/WebSocketHandlerTests.swift, FlyingFox/Tests/WebSocket/WSFrameEncoderTests.swift
Fixes typo in `WebSocketHTTPHandler` name
`WebSocketHTTPHander` -> `WebSocketHTTPHandler`
Adds unavailable declaration with the rename to assist any clients using it.
=> Fix WebSocketHTTPHandler Typo

FlyingFox/Tests/AsyncSocketTests.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingFox/Tests/WebSocket/WSFrameEncoderTests.swift, FlyingSocks/Sources/AsyncSocket.swift, FlyingSocks/Sources/PollingSocketPool.swift, FlyingSocks/Tests/AsyncSocketTests.swift
Allows `PollingSocketPool` to be created with 2 intervals;
- `pollInterval`: timeout passed to `poll(2)`
- `loopInterval`: Task.sleep timeout optional used for each loop iteration.
=> PollingSocketPool loop interval

.github/workflows/build.yml
Adds GitHub Actions job to build and run tests using Xcode 14 beta.
=> Xcode 14 Beta

FlyingFox/Sources/HTTPServer.swift, FlyingFox/Sources/Task+Timeout.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingFox/Tests/Task+TimeoutTests.swift, FlyingSocks/Sources/AsyncSocket.swift
Because FlyingFox uses structured concurrency care has been taken to ensure all child tasks run under a single parent task. The server starts and spawns 2 child tasks;
- run `AsyncSocketPool` enabling async sockets
- listen for connections
- each connect then gets its own task to process requests  
```
┌─────┐                       
│Start│                       
└─────┘                       
│                          
┌───────┴───────┐                  
▼               ▼                  
┌────────┐      ┌────────┐              
│  Pool  │      │ Listen │              
└────────┘      └────────┘              
│                  
┌────────────┼────────────┐     
│            │            │     
▼            ▼            ▼     
┌──────────┐ ┌──────────┐ ┌──────────┐
│Connection│ …
```
=> Stop server by allowing existing connections to disconnect first

FlyingFox/Sources/HTTPServer.swift, FlyingFox/Tests/HTTPServerTests.swift
Exposes the currently listening address of `HTTPServer`.  Once the server is started and listening the bound port can be retrieved;
```swift
let server = HTTPServer(address: .loopback(port: 0))
Task { try await server.run() }
try await server.waitUntilListening()
switch await server.listeningAddress {
case let .ip4(_, port: port),
let .ip6(_, port: port):
return port
default:
return nil
}
```
Many thanks to @karwa for the suggestion https://github.com/swhitty/FlyingFox/issues/41
=> HTTPServer listeningAddress

FlyingFox/Sources/HTTPServer.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingSocks/Sources/AsyncSocket.swift, FlyingSocks/Sources/EventQueue+kQueue.swift, FlyingSocks/Sources/EventQueueSocketPool.swift, FlyingSocks/Sources/PollingSocketPool.swift, FlyingSocks/Tests/EventQueue+kQueueTests.swift, FlyingSocks/Tests/EventQueueSocketPoolTests.swift
Adds a new `EventQueueSocketPool<Queue>` implementation allowing sockets to be monitored via kernel events.
This PR adds support for [`kqueue(2)`](https://www.freebsd.org/cgi/man.cgi?kqueue) on Darwin platforms. [`epoll(7)`](https://man7.org/linux/man-pages/man7/epoll.7.html) support will be added in the future.
`PollingSocketPool` remains the default pool used, but `HTTPServer` can be constructed with an event queue on Darwin:
```swift
let server = HTTPServer(port: 80, pool: makeEventQueuePool())
```
Event queues remove the need to continuously poll the awaiting file descriptors, instead a [DispatchQueue](https://developer.apple.com/documentation/dispatch/dispatchqueue) is used to wait indefinitely for any events to be returned from the queue.  Newly added file descriptors can be added …
=> AsyncSocketPool kqueue

CSystemLinux/include/CSystemLinux.h, CSystemLinux/include/module.modulemap, CSystemLinux/shims.c, FlyingSocks/Sources/EventQueue+ePoll.swift, FlyingSocks/Sources/EventQueueSocketPool.swift, Package.swift
Adds [`epoll(7)`](https://man7.org/linux/man-pages/man7/epoll.7.html) support on Linux platforms within `EventQueueSocketPool<Queue>`.  Darwin platforms can use `kqueue` - see: https://github.com/swhitty/FlyingFox/pull/44.
Allows `HTTPServer` to be constructed with an `epoll` queue on Linux platforms.
```swift
let server = HTTPServer(port: 80, pool: makeEventQueuePool())
```
=> AsyncSocketPool epoll

FlyingSocks/Sources/EventQueue+Poll.swift, FlyingSocks/Sources/EventQueue+ePoll.swift, FlyingSocks/Sources/EventQueue+kQueue.swift, FlyingSocks/Sources/EventQueueSocketPool.swift, FlyingSocks/Tests/EventQueue+PollTests.swift, FlyingSocks/Tests/EventQueue+kQueueTests.swift, FlyingSocks/Tests/EventQueueSocketPoolTests.swift
Adds [`poll(2)`](https://www.freebsd.org/cgi/man.cgi?poll) implementation of `protocol EventQueue` allowing `EventQueueSocketPool<Poll>` to replace `PollingSocketPool`.
Allows all platforms to construct an `EventQueueSocketPool<Queue>` with `makeEventQueuePool()`
- Darwin `EventQueueSocketPool<kQueue>`
- Linux `EventQueueSocketPool<ePoll>`
- Windows / Darwin / Linux `EventQueueSocketPool<Poll>`
=> POLL Queue

FlyingFox/Tests/AsyncSocketTests.swift, FlyingFox/Tests/HTTPConnectionTests.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingSocks/Sources/AsyncSocket.swift, FlyingSocks/Sources/PollingSocketPool.swift, FlyingSocks/Sources/SocketPool.swift, FlyingSocks/Tests/AsyncSocketTests.swift
replaces `.pollingClient: AsyncSocketPool` with `.client: some AsyncSocketPool { get async throws }` enabling a the shared pool to be managed by `ClientPoolLoader` and clients can now wait for the pool to be prepared before attempting to use it.
=> ClientPoolLoader

FlyingFox/Sources/Handlers/FileHTTPHandler.swift, FlyingFox/Tests/Handlers/HTTPHandlerTests.swift
Adds automatic support for `Content-Type: text/css` when file extension is `.css`
https://github.com/swhitty/FlyingFox/issues/52
=> Add support for text/css within FileHTTPHandler

FlyingFox/Sources/Handlers/DirectoryHTTPHandler.swift, FlyingFox/Tests/Handlers/DirectoryHTTPHandlerTests.swift, FlyingFox/Tests/Handlers/HTTPHandlerTests.swift
The [README.md](https://github.com/swhitty/FlyingFox/blob/main/README.md) states that route can be easily created to a directory like so:
```swift
await server.appendRoute("GET /mock/*", to: .directory(subPath: "Stubs", serverPath: "mock"))
```
This currently does not work because the `serverPath` requires a leading `/` e.g. `serverPath: "/mock"`
This is rather unintuitive because `HTTPRoute` internally matches routes ignoring leading the trailing `/` delimiters so `DirectoryHTTPHandler` should be able to as well.
https://github.com/swhitty/FlyingFox/issues/49
=> DirectoryHTTPHandler improvements

FlyingFox/Sources/HTTPBodySequence.swift, FlyingFox/Sources/HTTPDecoder.swift, FlyingFox/Sources/HTTPEncoder.swift, FlyingFox/Sources/HTTPRequest.swift, FlyingFox/Sources/HTTPRoute.swift, FlyingFox/Sources/HTTPServer.swift, FlyingFox/Tests/HTTPBodySequenceTests.swift, FlyingFox/Tests/HTTPConnectionTests.swift, FlyingFox/Tests/HTTPEncoderTests.swift, FlyingFox/Tests/HTTPRequestTests.swift, FlyingSocks/Sources/AsyncDataSequence.swift, FlyingSocks/Tests/AsyncDataSequenceTests.swift
In current versions ([0.10.0](https://github.com/swhitty/FlyingFox/releases/tag/0.10.0) and earlier) each `HTTPRequest` instance includes the entire request body within the `var body: Data` property limiting the size of requests that can be processed.
This PR introduces `HTTPBodySequence` that can represent the body of requests as an `AsyncSequence` of `Data` elements allowing request handlers to process the body in chunks as it is uploaded:
```swift
func saveBody(request: HTTPRequest) async throws -> HTTPResponse {
let file =  URL(fileURLWithPath: "/tmp/file")
_ = FileManager.default.createFile(atPath: file.path, contents: nil)
let handle = try FileHandle(forWritingTo: file)
defer { try? handle.close() }
for try await chunk in req.bodySequence {
try handle.write(contentsOf: chunk)
}
} …
```
=> HTTPBodySequence to enable very large requests

FlyingFox/Sources/HTTPBodySequence.swift, FlyingFox/Sources/HTTPConnection.swift, FlyingFox/Sources/HTTPEncoder.swift, FlyingFox/Sources/HTTPResponse.swift, FlyingFox/Sources/Handlers/FileHTTPHandler.swift, FlyingFox/Tests/HTTPBodySequenceTests.swift, FlyingFox/Tests/HTTPConnectionTests.swift, FlyingFox/Tests/HTTPDecoderTests.swift, FlyingFox/Tests/HTTPEncoderTests.swift, FlyingFox/Tests/HTTPResponse+Mock.swift, FlyingFox/Tests/HTTPResponseTests.swift, FlyingFox/Tests/Handlers/DirectoryHTTPHandlerTests.swift, FlyingFox/Tests/Handlers/HTTPHandlerTests.swift, FlyingFox/Tests/WebSocket/WSHandlerTests.swift, FlyingSocks/Sources/AsyncDataSequence.swift, FlyingSocks/Tests/AsyncDataSequenceTests.swift, FlyingSocks/Tests/Resources/JackOfHeartsRecital.txt, Package.swift
In current versions ([0.10.0](https://github.com/swhitty/FlyingFox/releases/tag/0.10.0) and earlier) each HTTPResponse instance includes the entire response body within the var payload: Payload property limiting the size of responses that can be returned.
[PR#56 ](https://github.com/swhitty/FlyingFox/pull/56) added `HTTPBodySequence` allowing the body of requests to be backed by either a complete `Data` instance, or from the underlying socket serving the request.
This PR updates `HTTPResponse` so that its `payload` property can now be a `HTTPBodySequence` instance allowing large files on disk to be streamed in the response:
```swift
HTTPResponse(
statusCode: .ok,
body: try HTTPBodySequence(file: URL(fileURLWithPath: "/Users/swhitty/Downloads/Xcode_14.3.xip"))
)
```
`FileHTTPHandler` has …
=> HTTPBodySequence to enable very large responses

FlyingSocks/Sources/SocketAddress.swift
The `UnsafeMutablePointer` instances should be deallocated once they are no longer needed.
=> Fix buffer leak

FlyingFox/Sources/HTTPServer.swift, FlyingFox/Tests/HTTPServerTests.swift
Sockets cannot be closed multiple times. The listening socket of `HTTPServer` is closed in both `stop() async` and if an error is thrown in `start() async throws` — the socket is now only closed once and then the reference is removed preventing the another close attempt.
=> Sockets must only be closed a single time

.github/workflows/build.yml, README.md
Add GitHub Action build using linux[ `swift:5.9`](https://hub.docker.com/_/swift/) image.
=> Add Github Action Build for Swift 5.9

.swiftpm/xcode/xcshareddata/xcschemes/FlyingFox-Package.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/FlyingFox.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/FlyingSocks.xcscheme, FlyingFox/Sources/Handlers/HTTPHandlerMacro.swift, FlyingFox/Tests/Handlers/HTTPHandlerMacroTests.swift, Macro/Sources/CustomError.swift, Macro/Sources/FunctionDecl.swift, Macro/Sources/HTTPHandlerMacro.swift, Macro/Sources/HTTPRouteMacro.swift, Macro/Sources/JSONRouteMacro.swift, Macro/Sources/Plugin.swift, Package.resolved, Package@swift-5.9.swift, README.md
An experimental preview of `@HTTPRoute` and  `@JSONRoute` to annotate functions with routes. 
The annotations are implemented via [SE-0389 Attached Macros](https://github.com/apple/swift-evolution/blob/main/proposals/0389-attached-macros.md) available in Swift 5.9 and later. 
A handler is able to annotate its functions with routes:
```swift
@HTTPHandler
struct MyHandler {
@HTTPRoute("/ping")
func ping() { }
@HTTPRoute("/pong")
func getPong(_ request: HTTPRequest) -> HTTPResponse {
HTTPResponse(statusCode: .accepted)
}
}
let server = HTTPServer(port: 80, handler: MyHandler())
try await server.start()
```
The macro synthesises conformance to `HTTPHandler` delegating handling to the first matching route. Expanding the example above to the following:
```swift
// expanded macro synthesis
func …
```
=> Handler Macro (@HTTPRoute / @JSONRoute)

FlyingFox/Sources/HTTPDecoder.swift, FlyingFox/Sources/HTTPRoute.swift, FlyingFox/Tests/HTTPDecoderTests.swift, FlyingFox/Tests/HTTPRouteTests.swift
Adds support for parsing requests with percent encoded paths.
Routes can be added including spaces:
```swift
server.appendRoute("/fish & chips") { _ in
HTTPResponse(
statusCode: .ok,
headers: [.contentType: "text/plain; charset=UTF-8"],
body: "🐟🍟".data(using: .utf8)!
)
}
```
Requests are decoded and matched against the unescaped Routes:
```
% curl "localhost/fish%20&%20chips"
🐟🍟
```
Resolves #74
=> Support Percent Encoded Paths

FlyingFox/Sources/Handlers/ProxyHTTPHandler.swift, FlyingFox/Sources/URLSession+Async.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingFox/Tests/URLSession+AsyncTests.swift, FlyingSocks/Sources/AllocatedLock.swift, FlyingSocks/Tests/AllocatedLockTests.swift
Xcode 14.1 [@backdeploy](https://github.com/apple/swift-evolution/blob/main/proposals/0376-function-back-deployment.md)'s [`URLSession.data(for:delegate:)`](https://developer.apple.com/documentation/foundation/urlsession/3767352-data) to iOS 13 so the fallback method can now be compiled only on Linux/Windows.  macOS builds can always use the Foundation version.
Adds `@spi(Private)` version of [AllocatedLock](https://github.com/swhitty/AllocatedLock) to FlyingSocks making a fast cross platform lock implementation available for all platforms.
=> Remove backported method

FlyingFox/Sources/Handlers/RoutedHTTPHandler.swift, FlyingFox/Tests/Handlers/RoutedHTTPHandlerTests.swift
Adds new methods to `RoutedHTTPHandler` to allow routes to be inserted at any `Index`.
```swift
public mutating func insertRoute(_ route: HTTPRoute, 
at index: Index,
to handler: some HTTPHandler) { }
public mutating func insertRoute(_ route: HTTPRoute,
at index: Index,
handler: @Sendable @escaping (HTTPRequest) async throws -> HTTPResponse) { }
```
Adds conformance to [`RangeReplaceableCollection`](https://developer.apple.com/documentation/swift/rangereplaceablecollection) which exposes most of the methods of the underlying array used to store the routes;
```swift
let handler = RoutedHTTPHandler()
...
handler.removeAll()
handler.removeFirst(2)
handler.popLast()
```
=> RoutedHTTPHandler implements RangeReplaceableCollection

FlyingFox/Sources/HTTPServer+Listening.swift, FlyingFox/Sources/HTTPServer.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingSocks/Sources/IdentifiableContinuation.swift, FlyingSocks/Sources/SocketPool.swift, FlyingSocks/Tests/IdentifiableContinuationTests.swift
Adds implementation & tests from [swhitty/IdentifiableContinuation ](https://github.com/swhitty/IdentifiableContinuation) providing a cleaner way to implement continuation with task cancellation.
=> IdentifiableContinuation

FlyingSocks/Sources/SocketPool.swift
Replaces `CancellingContinuation` with `IdentifiableContinuation` within the `SocketPool` loop
=> SocketPool Loop + IdentifiableContinuation

FlyingSocks/Sources/SocketPool.swift, FlyingSocks/Tests/SocketPoolTests.swift
Replaces usage of `CancellingContinuation` with `IdentifiableContinuation` within `SocketPool` when suspending sockets.
=> SocketPool + IdentifiableContinuation

FlyingSocks/Sources/SocketPool+Poll.swift, FlyingSocks/Sources/SocketPool+ePoll.swift, FlyingSocks/Sources/SocketPool+kQueue.swift, FlyingSocks/Sources/SocketPool.swift, FlyingSocks/Tests/SocketPool+PollTests.swift, FlyingSocks/Tests/SocketPool+kQueueTests.swift, FlyingSocks/Tests/SocketPoolTests.swift
It is not safe to close ePOLL queue concurrently while waiting for events, it should be stopped first.  A future PR will add that logic.
`stop()` is added in place of existing `close()`
=> Introduce EventQueue.stop()

FlyingFox/Sources/HTTPClient.swift, FlyingFox/Tests/AsyncSocketTests.swift, FlyingFox/Tests/HTTPClientTests.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingFox/Tests/WebSocket/WSFrameEncoderTests.swift
Adds a private API (not supported publicly) that demonstrates how to use FlyingFox as a HTTPClient.
For example, if a server was running on `localhost:8080`, its possible to send a `HTTPRequest` and receive a `HTTPResponse`
```swift
@_spi(Private) import struct FlyingFox._HTTPClient
let client = _HTTPClient()
let response = try await client.sendHTTPRequest(HTTPRequest(path: "/hello"), to: .loopback(port: 8080))
```
=> @_spi(Private) _HTTPClient

FlyingFox/Sources/HTTPMethod.swift, FlyingFox/Sources/HTTPRoute.swift, FlyingFox/Sources/HTTPServer.swift, FlyingFox/Sources/Handlers/RoutedHTTPHandler.swift, FlyingFox/Tests/HTTPRouteTests.swift, FlyingFox/Tests/Handlers/RoutedHTTPHandlerTests.swift
As discussed in #90, this PR proposes to make the `HTTPRoute.method` property of type `Set<HTTPMethod>`.
To do this, I've added a few things:
- `HTTPMethod ` is now `ExpressibleByStringLiteral`.
- `HTTPMethod` now ignores the case of its raw value when checking for equality.
I still need to update the documentation around this, but the tests are passing.
=> Change HTTPRoute.method to be of type HTTPMethod

FlyingFox/Sources/HTTPBodySequence.swift, FlyingFox/Sources/HTTPConnection.swift, FlyingFox/Sources/HTTPDecoder.swift, FlyingFox/Sources/HTTPRoute.swift, FlyingFox/Sources/WebSocket/AsyncStream+WSFrame.swift, FlyingFox/Sources/WebSocket/WSFrameEncoder.swift, FlyingFox/Tests/ConsumingAsyncSequence.swift, FlyingFox/Tests/HTTPBodySequenceTests.swift, FlyingFox/Tests/HTTPDecoderTests.swift, FlyingSocks/Sources/AsyncBufferedCollection.swift, FlyingSocks/Sources/AsyncBufferedDataSequence.swift, FlyingSocks/Sources/AsyncBufferedSequence.swift, FlyingSocks/Sources/AsyncChunkedSequence.swift, FlyingSocks/Sources/AsyncDataSequence.swift, FlyingSocks/Sources/AsyncSocket.swift, FlyingSocks/Tests/AsyncBufferedDataSequenceTests.swift, FlyingSocks/Tests/AsyncDataSequenceTests.swift
Deprecates `AsyncChunkedSequence` replacing it with `AsyncBufferedSequence`.
```swift
public protocol AsyncBufferedIteratorProtocol: AsyncIteratorProtocol {
// Buffered elements are returned in this collection type
associatedtype Buffer: Collection where Buffer.Element == Element
/// Retrieves available elements from the buffer. Suspends if 0 elements are available.
/// - Parameter count: The maximum number of elements to return
/// - Returns: Array with between 1 and the number elements that was requested. Nil is returned if the sequence has ended.
mutating func nextBuffer(atMost count: Int) async throws -> Buffer?
}
```
=> AsyncChunkedSequence -> AsyncBufferedSequence

FlyingFox/Sources/HTTPBodySequence.swift, FlyingFox/Sources/HTTPChunkedEncodedSequence.swift, FlyingFox/Sources/HTTPEncoder.swift, FlyingFox/Sources/HTTPHeader.swift, FlyingFox/Tests/HTTPEncoderTests.swift, FlyingFox/Tests/HTTPResponse+Mock.swift
Adds support for `HTTPResponse` payloads to be encoded with `Transfer-Encoding: chunked` which removes the need for `Content-Length` being known up front.  
The body must be provided from aa `HTTPBodySequence` from `some AsyncBufferedSequence<UInt8>` without specifying size. The response is then chunked like so:
```
HTTP/1.1 200 OK\r
Transfer-Encoding: chunked\r
\r
0A\r
Hello Worl\r
02\r
d!\r
0\r
\r
```
The client detects end from `0\r\n\r\n`
An example of the above response without chunked encoding is:
```
GET /hello/world HTTP/1.1\r
Content-Length: 5
\r
Hello
```
=> HTTPResponse support for Transfer-Encoding: chunked

Package.swift
While we don't run CI and test against watchOS, FlyingFox does work and is useful for SwiftUI previews so we can declare support for it within Package.swift
=> add SPM support for watchOS

FlyingFox/Sources/HTTPEncoder.swift, FlyingFox/Sources/HTTPHeader.swift, FlyingFox/Sources/HTTPRoute.swift, FlyingFox/Tests/HTTPEncoderTests.swift, FlyingFox/Tests/HTTPHeaderTests.swift, FlyingFox/Tests/HTTPRouteTests.swift
Adds support for multiple, comma delimited values for HTTP headers.
Because `HTTPRequest` and `HTTPResponse` represents all headers as `[HTTPHeader: String]` the support is added by extending this dictionary with additional methods:
```swift
request.headers.addValue("fish", for: .contentType)
request.headers.addValue("chips", for: .contentType)
request.headers[.contentType] == "fish, chips"
```
=> Support multiple values for the same HTTPHeader

FlyingFox/Sources/HTTPBodySequence.swift, FlyingFox/Sources/HTTPChunkedEncodedSequence.swift, FlyingFox/Tests/ConsumingAsyncSequence.swift, FlyingFox/Tests/HTTPDecoderTests.swift, FlyingSocks/Sources/AsyncBufferedCollection.swift, FlyingSocks/Sources/AsyncBufferedSequence.swift, FlyingSocks/Sources/AsyncDataSequence.swift, FlyingSocks/Sources/AsyncSocket.swift, FlyingSocks/Tests/AsyncBufferedDataSequenceTests.swift, FlyingSocks/Tests/AsyncDataSequenceTests.swift
Updates `AsyncBufferedSequence` added in https://github.com/swhitty/FlyingFox/pull/95 to use a "suggested" buffer size, allowing the caller to return more or less than the suggested size
```swift
mutating func nextBuffer(suggested count: Int) async throws -> Buffer?
```
=> AsyncBufferedSequence suggested size

FlyingFox/Sources/HTTPRequestParameter.swift, FlyingFox/Sources/HTTPServer.swift, FlyingFox/Sources/Handlers/RoutedHTTPHandler.swift, FlyingFox/Tests/HTTPRouteTests.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingFox/Tests/Handlers/RoutedHTTPHandlerTests.swift
Swift 5.9+
Extends support for path parameters https://github.com/swhitty/FlyingFox/pull/94 by using parameter packs to route to closures.
Closures must include arguments that conform to `HTTPRequestParameter` (currently only `String` and `Int` conform) and the parameter will be automatically extracted from the path and passed to the closure:
```swift
await server.appendRoute("/fish/:id") { (id: String) in
HTTPResponse.make(statusCode: .ok, body: "Hello \(id)".data(using: .utf8)!)
}
```
Making a request to `GET /fish/chips` will result in a response body `Hello chips`
=> Route to Parameter Pack handlers

FlyingFox/Sources/HTTPRequest+RouteParameter.swift, FlyingFox/Sources/HTTPRequest.swift, FlyingFox/Sources/HTTPRequestParameter.swift, FlyingFox/Sources/HTTPRoute.swift, FlyingFox/Sources/Handlers/RoutedHTTPHandler.swift, FlyingFox/Tests/HTTPRequestTests.swift, FlyingFox/Tests/HTTPRouteTests.swift, FlyingFox/Tests/Handlers/RoutedHTTPHandlerTests.swift
Building on https://github.com/swhitty/FlyingFox/pull/94 it is now super easy to also add parameters to query string allowing for:
```swift
handler.appendRoute("GET /greeting?id=:name") { request in
let name = request.queryParameter(for: "name")
return HTTPResponse(statusCode: .ok, body: "Hello \(name)".data(using: .utf8)!)
}
```
While it may seem redundant it allows us to bind that parameter directly to a parameter pack
```swift
handler.appendRoute("GET /greeting?id=:name") { (name: String) -> HTTPResponse in
HTTPResponse(statusCode: .ok, body: "Hello \(name)".data(using: .utf8)!)
}
```
Thinking about it more, there may be no need to split the parameters out into path / query sets:
```swift
public func pathParameter(for identifier: String) -> String?  { }
public func queryParameter(for …
```
=> Add support for parameters in query string

FlyingSocks/Sources/SocketPool+Poll.swift
Socket+Poll.swift requires the WinSock2 library to be imported for compilation. This allows the poll objects to be recognized by Windows while building.
=> Fix Windows build

FlyingFox/Sources/HTTPServer.swift
I was trying to switch our project's dependency of FlyingFox away from our fork ([PR](https://github.com/EmergeTools/SnapshotPreviews-iOS/pull/137)), but encountered this error in CI:
=> add watchOS 10 available check for withThrowingDiscardingTaskGroup call

FlyingFox/Sources/HTTPConnection.swift, FlyingFox/Sources/HTTPHeader.swift, FlyingFox/Sources/HTTPRequest+Address.swift, FlyingFox/Sources/HTTPRequest.swift, FlyingFox/Tests/HTTPRequest+AddressTests.swift, FlyingFox/Tests/HTTPServerTests.swift
Adds `HTTPRequest.remoteAddress` allowing handlers to receive the address and port of the remove client making the request.
`HTTPRequest.remoteIPAddress` is also added as a convenience, preferring the client value from the `X-Forwarded-For` header which is useful for handlers running behind a reverse proxy.
=> HTTPRequest.Address including X-Forwarded-For

FlyingFox/Sources/HTTPBodySequence.swift, FlyingFox/Sources/HTTPClient.swift, FlyingFox/Sources/HTTPConnection.swift, FlyingFox/Sources/HTTPServer+Listening.swift, FlyingFox/Sources/HTTPServer.swift, FlyingFox/Sources/URLSession+Async.swift, FlyingFox/Tests/HTTPBodySequenceTests.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingFox/Tests/WebSocket/WSFrameEncoderTests.swift, FlyingSocks/Sources/AllocatedLock.swift, FlyingSocks/Sources/AsyncBufferedCollection.swift, FlyingSocks/Sources/AsyncDataSequence.swift, FlyingSocks/Sources/IdentifiableContinuation.swift, FlyingSocks/Sources/Task+Timeout.swift, FlyingSocks/Tests/AllocatedLockTests.swift, FlyingSocks/Tests/AsyncBufferedDataSequenceTests.swift, FlyingSocks/Tests/AsyncDataSequenceTests.swift, FlyingSocks/Tests/IdentifiableContinuationTests.swift, FlyingSocks/Tests/SocketPoolTests.swift, FlyingSocks/Tests/Task+TimeoutTests.swift
Now that Swift 5.9 is the minimum supported language version we can replace all `spi(private)` with `package` from [SE-0386](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0386-package-access-modifier.md)
=> package access control

FlyingSocks/Sources/SocketAddress.swift, FlyingSocks/Tests/SocketAddressTests.swift
**Given**
FlyingFox: 0.14.0
Device: iPhone 15 iOS 17.5 (Simulator)
**When**
Turn on **AddressSanitizer** in **Xcode**.
**Then**
I've encountered a dynamic stack buffer overflow error.
```assembly
Address 0x00016cead4bc is located in stack of thread T0
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow (/Users/__WHOAMI__/Library/Developer/CoreSimulator/Devices/95E3F30B-6F79-410F-8A4C-68EC8706820E/data/Containers/Bundle/Application/560390B8-52F3-4465-9BD6-82AA4A9EB557/__APP__.app/__APP__:arm64+0x103471ea4) in closure #1 (Swift.UnsafePointer<__C.sockaddr_storage>) -> __C.sockaddr_storage in closure #1 (Swift.UnsafePointer<A>) -> __C.sockaddr_storage in (extension in FlyingSocks):FlyingSocks.SocketAddress.makeStorage() -> __C.sockaddr_storage+0x9b0
Shadow bytes around the buggy address: …
```
=> Fix: Dynamic Stack Buffer Overflow

FlyingFox/Sources/HTTPServer+Configuration.swift, FlyingFox/Sources/HTTPServer.swift, FlyingSocks/Sources/AsyncSocket.swift, FlyingSocks/Sources/Socket.swift, FlyingSocks/Sources/SocketAddress.swift, FlyingSocks/Tests/SocketAddressTests.swift, FlyingSocks/Tests/SocketTests.swift
`sockaddr_storage` is only really used as box for any address, but since [SE-0352](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0352-implicit-open-existentials.md) we can now just use `any SocketAddress` and let the compiler box / unbox from an existential.
`HTTPServer.Configuration` is now added to encapsulate the growing number of properties used to start `HTTPServer`.
The recently fixed `func makeStorage() -> sockaddr_storage` from https://github.com/swhitty/FlyingFox/pull/109 has been moved to unit tests.
=> move makeStorage() to tests

FlyingFox/Sources/AsyncSequence+Extensions.swift, FlyingFox/Tests/AsyncSequence+ExtensionsTests.swift, FlyingFox/Tests/HTTPBodySequenceTests.swift, FlyingFox/Tests/HTTPRequestTests.swift, FlyingSocks/Sources/AllocatedLock.swift, FlyingSocks/Sources/ConsumingAsyncSequence.swift, FlyingSocks/Tests/AsyncDataSequenceTests.swift
Updates `ConsumingAsyncSequence` which is only used in unit tests.  It now wraps `any AsyncBufferedSequence` allowing it to be used with more sequences
=> ConsumingAsyncSequence (used in unit tests)

FlyingFox/Sources/HTTPBodySequence.swift, FlyingFox/Tests/HTTPBodySequenceTests.swift, FlyingSocks/Sources/AsyncBufferedFileSequence.swift, FlyingSocks/Sources/AsyncBufferedSequence+Extensions.swift, FlyingSocks/Sources/AsyncDataSequence.swift, FlyingSocks/Tests/AsyncBufferedFileSequenceTests.swift, FlyingSocks/Tests/AsyncDataSequenceTests.swift
Adds a dedicated `AsyncBufferedFileSequence` used within `HTTPResponse` when returning large files.  The sequence replaces some legacy logic in the soon to be removed `AsyncDataSequence`
=> AsyncBufferedFileSequence (used in HTTPResponses to large files)

FlyingFox/Sources/WebSocket/WSMessage.swift
=> Make EchoWSMessageHandler initializer public

.github/workflows/build.yml, Package.swift
Updates GitHub Actions to use the official `swift:6.0` docker image
Enables Swift Testing when using Swift 6 on linux.
=> Official Swift 6.0 Docker Image

FlyingFox/Sources/HTTPServer.swift, FlyingFox/Tests/HTTPClientTests.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingFox/XCTests/HTTPClientTests.swift, FlyingFox/XCTests/HTTPServerTests.swift, README.md
Deprecates `HTTPServer.start()` and offers the renamed `HTTPServer.run()`  for compatibility with [swift-service-lifecycle](https://github.com/swift-server/swift-service-lifecycle)
=> rename HTTPServer.start() -> run()

FlyingFox/Sources/WebSocket/WSFrameEncoder.swift, FlyingFox/Tests/WebSocket/WSFrameEncoderTests.swift, FlyingFox/XCTests/WebSocket/WSFrameEncoderTests.swift
It must be interpreted as big-endian (network byte order).
=> Fix WebSocket frame length byte order for 16-bit length case

FlyingSocks/Sources/Socket.swift
Currently `protocol SocketOption` and `socket.setValue` / `socket.getValue` all assume the hardcoded level `SOL_SOCKET`.
This PR allows each option to provide its own level, while defaulting to `SOL_SOCKET` if not supplied by clients.
This enables `protocol SocketOption` and related API to be used for setting `ip_pktinfo/ipv6_pktinfo`
=> SocketOption level

FlyingSocks/Sources/Socket+Android.swift, FlyingSocks/Sources/Socket+Darwin.swift, FlyingSocks/Sources/Socket+Glibc.swift, FlyingSocks/Sources/Socket+Musl.swift, FlyingSocks/Sources/Socket+WinSock2.swift, FlyingSocks/Sources/Socket.swift
Haven't tested, try this though.
=> IPV6_RECVPKTINFO is the correct option to receive IPV6_PKTINFO

FlyingSocks/Sources/Socket.swift, FlyingSocks/Tests/SocketTests.swift, FlyingSocks/XCTests/SocketTests.swift
After some[ recent refactoring](https://github.com/swhitty/FlyingFox/pull/130) we can now get and set the packetInfo via the existing the existing `protocol SocketOption` / `setValue()` API.
UDP sockets still enable these options by default within `.init()` but users can now easily read and change the values like so:
```swift
let socket = try Socket(domain: AF_INET, type: .datagram)
try socket.getValue(for: .packetInfoIP) == true
try socket.setValue(false, for: .packetInfoIP)
try socket.getValue(for: .packetInfoIP) == false
```
Unit tests have been added to cover this case.
=> convert setPktInfo() to SocketOption

.github/workflows/build.yml
Support for building with an Android SDK was added by @lhoward within https://github.com/swhitty/FlyingFox/pull/127.
This PR updates the GitHub actions config to include an additional build using the Android using [swift-android-sdk](https://github.com/finagolfin/swift-android-sdk) by @finagolfin 🙏🏻.
=> Android SDK build within GitHub Actions

FlyingSocks/Sources/AsyncSocket.swift, FlyingSocks/Sources/Socket.swift
`struct AnySocketAddress` should not be needed as `any SocketAddress` can box all addresses and can then be unwrapped to `sockaddr_storage` when required to be used.
replace `(some SocketAddress)? = nil` with `(any SocketAddress)? = nil` so callers of this method do not need to provide a concrete type and can instead provide `nil`
=> remove AnySocketAddress

FlyingSocks/Sources/AsyncSocket.swift, FlyingSocks/Tests/AsyncSocketTests.swift
Updates `AsyncSocket.Message` to expose its bytes as `payload: Data`.
Extends the existing datagram tests to better cover `sendMessage()`.  
For these datagram tests:
- Darwin uses `AF_INET6` sockets
- Linux uses `AF_UNIX` pair.
=> More datagram tests

FlyingFox/Sources/HTTPDecoder.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingSocks/Sources/AsyncBufferedPrefixSequence.swift, FlyingSocks/Tests/AsyncBufferedPrefixSequenceTests.swift
fixes https://github.com/swhitty/FlyingFox/issues/139
`HTTPRequest.bodySequence` is aways backed by one of the the following concrete types:
- [`AsyncSharedReplaySequence`](https://github.com/swhitty/FlyingFox/blob/main/FlyingSocks/Sources/AsyncSharedReplaySequence.swift): Sequence that can be safely iterated multiple times by one or more consumers concurrently.  It is buffered in memory and is used for all requests with body less than `2_097_152` bytes https://github.com/swhitty/FlyingFox/blob/fe9437def670a54f17a135135e9c8127cc817962/FlyingFox/Sources/HTTPServer%2BConfiguration.swift#L46
- [`AsyncSocketReadSequence`](https://github.com/swhitty/FlyingFox/blob/fe9437def670a54f17a135135e9c8127cc817962/FlyingSocks/Sources/AsyncSocket.swift#L323) Sequence that is backed directly by the socket …
=> Fix HTTPBodySequence for large requests (adds AsyncBufferedPrefixSequence)

FlyingFox/Sources/HTTPClient.swift, FlyingFox/Sources/HTTPDecoder.swift, FlyingFox/Sources/HTTPRoute.swift, FlyingFox/Sources/HTTPServer+Configuration.swift, FlyingFox/Sources/HTTPServer.swift, FlyingFox/Tests/HTTPConnectionTests.swift, FlyingFox/Tests/HTTPDecoderTests.swift, FlyingFox/Tests/HTTPRequest+Mock.swift, FlyingFox/XCTests/HTTPConnectionTests.swift, FlyingFox/XCTests/HTTPDecoderTests.swift, FlyingFox/XCTests/HTTPRequest+Mock.swift
`HTTPRequest` currently provides access to the body via `HTTPBodySequence`, this sequence is currently backed by 2 concrete sequences:
- [`AsyncSharedReplaySequence`](https://github.com/swhitty/FlyingFox/blob/main/FlyingSocks/Sources/AsyncSharedReplaySequence.swift): Sequence that can be safely iterated multiple times by one or more consumers concurrently.  It is buffered in memory and is used for all requests with body less than `2_097_152` bytes https://github.com/swhitty/FlyingFox/blob/fe9437def670a54f17a135135e9c8127cc817962/FlyingFox/Sources/HTTPServer%2BConfiguration.swift#L46
- [`AsyncSocketReadSequence`](https://github.com/swhitty/FlyingFox/blob/fe9437def670a54f17a135135e9c8127cc817962/FlyingSocks/Sources/AsyncSocket.swift#L323) Sequence that is backed directly by the socket …
=> Buffer HTTPRequest.body < 4096 bytes as Data

FlyingFox/Sources/WebSocket/WSCloseCode.swift, FlyingFox/Sources/WebSocket/WSFrame.swift, FlyingFox/Sources/WebSocket/WSHandler.swift, FlyingFox/Sources/WebSocket/WSMessage.swift, FlyingFox/Tests/WebSocket/WSFrameTests.swift, FlyingFox/Tests/WebSocket/WSHandlerTests.swift, FlyingFox/XCTests/WebSocket/WSFrameTests.swift, FlyingFox/XCTests/WebSocket/WSHandlerTests.swift
First requested within: https://github.com/swhitty/FlyingFox/issues/137
Adds new case to `WSMessage` slowing servers to send and receive custom close codes sent by clients;
```swift
case close(code: WSCloseCode = .normalClosure, reason: String = "")
```
Adds `WSCloseCode` to represent the common codes, but allowing any `UInt16` to be sent.
=> WSMessage.close and WSCloseCode

FlyingFox/Sources/WebSocket/WSCloseCode.swift, FlyingFox/Sources/WebSocket/WSFrame.swift, FlyingFox/Sources/WebSocket/WSHandler.swift, FlyingFox/Sources/WebSocket/WSMessage.swift, FlyingFox/Tests/WebSocket/WSFrameTests.swift, FlyingFox/Tests/WebSocket/WSHandlerTests.swift, FlyingFox/XCTests/WebSocket/WSFrameTests.swift, FlyingFox/XCTests/WebSocket/WSHandlerTests.swift
Aligning within [HTTPStatusCode](https://github.com/swhitty/FlyingFox/blob/7d98b0c8585a1e516c3dd34d1585907908f9cd53/FlyingFox/Sources/HTTPStatusCode.swift#L32), `WSCloseCode` now includes the reason within the structure making it easier to pass around:
```swift
public struct WSCloseCode: Sendable, Hashable {
public var code: UInt16
public var reason: String
public init(_ code: UInt16) {
self.code = code
self.reason = ""
}
public init(_ code: UInt16, reason: String) {
self.code = code
self.reason = reason
}
}
```
Additionally closes the stream when a close message is sent to client
=> Include reason within WSCloseCode

FlyingSocks/Sources/SocketAddress.swift
Helpful for those who need a cross-platform way of unlinking a Unix address!
=> Expose Socket.unlink(...) as public

FlyingSocks/Sources/Mutex.swift, FlyingSocks/Sources/Socket+WinSock2.swift, FlyingSocks/Sources/Socket.swift, FlyingSocks/Tests/FileManager+TemporaryFile.swift, FlyingSocks/Tests/SocketErrorTests.swift, FlyingSocks/Tests/SocketPool+PollTests.swift, FlyingSocks/Tests/SocketTests.swift
Something is deeply wrong with the `Poll` implementation for Windows and some tests hang indefinitely because of it, I think. But at least it compiles and passes *some* of the many tests!
=> Get Windows to actually compile and pass some tests

.github/workflows/build.yml, FlyingFox/Sources/HTTPServer.swift, FlyingFox/Tests/HTTPServerTests.swift, FlyingSocks/Sources/Socket+WinSock2.swift, FlyingSocks/Sources/Socket.swift, FlyingSocks/Sources/SocketPool+Poll.swift, FlyingSocks/Tests/AsyncBufferedFileSequenceTests.swift, FlyingSocks/Tests/AsyncSocketTests.swift, FlyingSocks/Tests/SocketTests.swift
This brings greenlights to every test except datagram stuff.
Also fixes an edgecase affecting any user of `SocketPool<Poll>`
=> Many additional Windows fixes

.github/workflows/build.yml
Updates GitHub actions workflows for linux, android & windows to use Swift 6.1.
GitHub is still rolling out macOS agents with Xcode 16.3 so it is completely available yet.
=> Swift 6.1 on github actions

FlyingFox/Sources/HTTPBodySequence.swift, FlyingFox/Sources/HTTPEncoder.swift, FlyingFox/Sources/Handlers/FileHTTPHandler.swift, FlyingFox/Tests/Handlers/HTTPHandlerTests.swift, FlyingSocks/Sources/AsyncBufferedFileSequence.swift, FlyingSocks/Tests/AsyncBufferedFileSequenceTests.swift, FlyingSocks/XCTests/AsyncBufferedFileSequenceTests.swift
Updates `FileHTTPHandler` to support partial[ range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Range_requests).
Routes for both `GET` and  `HEAD` must be created to a file:
```swift
await server.appendRoute("GET,HEAD /jaws", to: .file(named: "jaws.m4v"))
```
When clients request the route and provide a `range` header
```http
GET /jaws HTTP/1.1
Host: localhost
Range: bytes=41000-49999
```
The response return just the requests bytes;
```http
HTTP/1.1 206 Partial Content
Content-Type: video/mp4
Content-Range: bytes 41000-49999/60000
Content-Length: 9000
Accept-Ranges: bytes
```
=> Update FileHTTPHandler to support partial range requests

FlyingFox/Sources/HTTPConnection.swift, FlyingFox/Sources/HTTPServer.swift, FlyingFox/Sources/Handlers/FileHTTPHandler.swift, FlyingFox/Tests/Handlers/HTTPHandlerTests.swift
Extends the HTTP ranged request support added in https://github.com/swhitty/FlyingFox/pull/157 to include support for offset only requests
This PR allows requests optionally provide an end of the range;
```http
GET /jaws HTTP/1.1
Host: localhost
Range: bytes=41000-
```
And a response will return everything to the end of the file.
```http
HTTP/1.1 206 Partial Content
Content-Type: video/mp4
Content-Range: bytes 41000-59999/60000
Content-Length: 19000
Accept-Ranges: bytes
```
=> Handle offset requests

FlyingFox/Sources/WebSocket/AsyncStream+WSFrame.swift, FlyingSocks/Sources/SocketPool.swift
Addresses Swift 6.2 warnings by conditionally conforming to `SendableMetatype` where required
=> Swift 6.2 SendableMetatype

FlyingSocks/Tests/AsyncSocketTests.swift, FlyingSocks/Tests/FileManager+TemporaryFile.swift, FlyingSocks/XCTests/AsyncSocketTests.swift
Replaces `mktemp` usage with `mkdtemp` to create a unique temporary directory.  Unix sockets are free to bind and a create a new file within that directory.
=> Use temp directory for unix socket tests

FlyingFox/Sources/Handlers/RoutedHTTPHandler.swift, FlyingFox/Tests/Handlers/RoutedHTTPHandlerTests.swift
https://github.com/swhitty/FlyingFox/pull/94 added support for "route parameters" within requests handled via `RoutedHTTPHandler`.
Requests handled manually could not use these route parameters because `HTTPRequest.matchedRoute` is internal only.  This PR adds a helper method `RoutedHTTPHandler.handleMatchedRequest()` that handles a request if the route matches, ensuring `HTTPRequest.matchedRoute` is set for the handler;
=> handleMatchedRequest

FlyingFox/Sources/HTTPEncoder.swift, FlyingFox/Sources/HTTPHeader.swift, FlyingFox/Sources/HTTPHeaders.swift, FlyingFox/Sources/HTTPRequest.swift, FlyingFox/Sources/HTTPResponse.swift, FlyingFox/Sources/HTTPRoute.swift, FlyingFox/Sources/Handlers/FileHTTPHandler.swift, FlyingFox/Sources/Handlers/WebSocketHTTPHandler.swift, FlyingFox/Tests/HTTPEncoderTests.swift, FlyingFox/Tests/HTTPHeaderTests.swift, FlyingFox/Tests/HTTPRequest+Mock.swift, FlyingFox/Tests/HTTPResponse+Mock.swift, FlyingFox/Tests/HTTPRouteTests.swift, FlyingFox/Tests/Handlers/HTTPHandlerTests.swift, FlyingFox/Tests/Handlers/WebSocketHTTPHandlerTests.swift, FlyingFox/XCTests/HTTPHeaderTests.swift, FlyingFox/XCTests/HTTPRequest+Mock.swift, FlyingFox/XCTests/HTTPRouteTests.swift, FlyingFox/XCTests/Handlers/WebSocketHTTPHandlerTests.swift
Replaces dictionary representations of headers  `[HTTPHeader: String]` with a type `HTTPHeaders` which continues to support subscript and dictionary literal API
```swift
let response = HTTPResponse(headers: [.contentEncoding: "xml"])
response.headers[.contentEncoding] // "xml"
```
But also supports appending multiple values which 
```swift
var headers = HTTPHeaders()
headers.addValue("fish" for: .setCookie)
headers.addValue("chips" for: .setCookie)
response.headers.values(for: .setCookie) == [
(header: .setCookie, value: "fish"),
(header: .setCookie, value: "chips"),
]
```
It continues to support combining (supported) headers into a comma delimited value
```swift
var headers = HTTPHeaders()
headers.addValue("xml" for: .contentEncoding)
headers.addValue("html" for: .contentEncoding) …
```
=> Multiple HTTPHeaders

FlyingFox/Sources/HTTPHandler.swift, FlyingFox/Sources/Handlers/RedirectHTTPHandler.swift, FlyingFox/Tests/Handlers/RedirectHTTPHandlerTests.swift, README.md
Updates `HTTPRedirectHandler` to dynamically redirect via a base URL
```swift
await server.appendRoute("GET /fish/*", to: .redirect(via: "https://pie.dev"))
// GET /fish/chips  --->  HTTP 301
//                        Location: https://pie.dev/fish/chips
```
Providing a serverPath allows for the removal of a prefix before redirecting:
```swift
await server.appendRoute("GET /fish/*", to: .redirect(via: "https://pie.dev", serverPath: "/fish"))
// GET /fish/chips  --->  HTTP 301
//                        Location: https://pie.dev/chips
```
=> Dynamic Redirect
